sudo: true
service: docker
language: ruby
cache:
- bundler
before_install:
- sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables
  -N DOCKER )
- gem install bundler -v 1.15
install:
- bundle install
rvm:
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
before_deploy:
- git clone https://github.com/sensu/sensu-go-bonsai-asset.git --branch feature/ruby-plugin-assets bonsai
script:
- gem build sensu-plugins-vault.gemspec
- gem install sensu-plugins-vault*.gem
- bundle exec rake quick
#- bundle exec rake kitchen:ruby-`echo $TRAVIS_RUBY_VERSION | sed -e "s/\.//g"`-debian-8
deploy:
  provider: rubygems
  api_key:
    secure: iXvvVJhGsNcWNLhX6EBFK9gWbvH5CRFFx53vqPD3uuEFiPB+U5TRLG5sLVeqOrkloQ05qbkjuPlW4BOf2McEw1eaxCuW0FhAfRJEfl4nnoUYx9nya3a0WU4Vq7rJaUclHusgGfUebEgLYBFpsOzzg0rXnAkv3tQ2fFkurxNIOjbB/lQAspHQJw86qePOLMT7OIt1v2fwuySwRHT+d+nyCmJ8yNpbkMK0BDbE2MuXmOVHJk6DsVY8mOi8CMQ7Mda7aQvWua+ECHf/KXnokNh9gUoqdppGmJ/7nrtOp3MKT1/B52AhSlm5aqrsXG5K4mQduHhp4vtK+zFs9M84CY+onyaKo+tLtEPgsisNDkZgUdvASHWWv2iIxjRyQggfs8mqwkoJvncGEHukPfsuo6cBAmDbKd9zZZjID9VC8PD7xql9meCNRP5UtEPPBsKji6uJ9CbRskVfFcVXJWhAz7aDs1cMUgY0j0VEmPY6MTAxKaQWkk3Vxe1wDe8U1nBud5zoQjoVCBx0wOrNzjEc5RmyIxJM7NrbvPzSzua/Olvhgb5j+0AgrQLXTsK9i/Sth8LzWt+WG5uE/cOinb6w4AL80XmunntqSIT3ADRbtqAhbPbaWc+7j5a/hywTiqoZuGxckLkRlvHqs3DeX1YUUnz+0ngVjSx82/mxbS493dH0i/8=
  gem: sensu-plugins-skel
  on:
    tags: true
    all_branches: true
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-skel
  provider: script
  script: bonsai/ruby-runtime/travis-build-ruby-plugin-assets.sh sensu-plugins-vault
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    rvm: 2.4.1
