sudo: true
service: docker
language: ruby
cache:
- bundler
before_install:
- sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables
  -N DOCKER )
- gem install bundler -v 1.15
install:
- bundle install
rvm:
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- gem build sensu-plugins-vault.gemspec
- gem install sensu-plugins-vault*.gem
- bundle exec rake quick
- bundle exec rake kitchen:ruby-`echo $TRAVIS_RUBY_VERSION | sed -e "s/\.//g"`-debian-8
deploy:
  provider: rubygems
  api_key:
    secure: apVfqhmIVfG3wZZkBCdvtzrfpA3V5kXs9cOFIAvas4Z9tXfLDiWnTSSQZvjlXqdMAm9HXBZeHQOnDPCl4ia2jd/USVX0MccA2wNHyKqb16cxOk5jCZYv7SgzcJrw8x4pfjKDmisYbWvTBJdk/Owl6sTEeUi/H7PTuwXmR1ZAmgKZR2JZG7ziQoFDSCwZR8tcYUTCaq+S9PeotcFxn35/TXh7Ya22jVVOS5iIRtGSrJi4H8MVp+rOJ6ZOXbYQT6GumzkkHTvta8HoIuwJHXT2jjD3DFVAuPd7MfiG1WB0KbmRNgqLN6uJ7yvtuF/2dg1J3FGEyAJod0oh46X8YkbJxDiGpgkk+HmNBBDpE3HBtpmfLzQNZjjknEfcbTxr+JD2c1xuckuSUX/fv7HSlpFy2v8ESNYROwXxBY5SoyaQ3TuT3vsmCIJ2ek8Jfqg80CvNHJ670YK3JMNGEK7HTNC5eYXz9eOyb20Cd/mmbWAFL2ooP4g9eJ9mEO+82OMjMPpD1QAya/9Cp2GisqrNrmp7g6U/OqQ9MliHoijr6PXy+kfY+TxdbBYOuLhJdfjEINKp9d3+9fOi7sMOg3IwmEUSFMFHcZtbUK96NlbgdsnunLbIVfz8q6s2m1XVzoh7q4BamTD6SqBP74vx7VaK3vl1FxXLlMLwxGV/5bEXUo88FHc=
  gem: sensu-plugins-vault
  on:
    tags: true
    all_branches: true
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-vault
